language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - g++-4.9
      - libcppunit-dev
      - libboost-system-dev
      - libgtest-dev

compiler:
  - g++

install:
  # g++4.9
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script:
  - cmake .; make clean; make UnitTest